Fixed reference counting when calling :py:meth:`multidict.MultiDict.update` -- by :user:`bdraco`.

The leak was introduced in 4.4.0